version: "3.9"
services:
    fastapi-db:
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi
        image: postgis/postgis:14-3.2-alpine
        ports:
            - "5433:5432"
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    fastapi-db-test:
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi-test
        image: postgis/postgis:14-3.2-alpine
        ports:
            - "5434:5432"
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    fastapi-core:
        build: .
        environment:
            - ANY_ENV_VAR_HERE
        env_file:
            - .env.ci
        ports:
            - "80:80"
        depends_on:
            fastapi-db:
                condition: "service_healthy"
            fastapi-db-test:
                condition: "service_healthy"
        networks:
            - backend

networks:
    backend: {}
